const templates = [
  {
    q: 'What was it like working with _blank_?', 
    a: [['language', 'company']]
  },
  {
    q: 'What was a challenge you faced working with _blank_?', 
    a: [['language', 'company']]
  },
  {
    q: 'What are your favourite aspects of _blank_?', 
    a: [['language']]
  },
  // {
  //   q: 'Why did you choose _blank_ in _blank_?', 
  //   a: [['language'],
  //       ['project']]
  // },
  {
    q: 'Why did you choose _blank_ in your work?', 
    a: [['language']]
  },
  {
    q: 'Can you tell me more about _blank_?', 
    a: [['company', 'project']]
  },
  {
    q: 'What was your favourite part about working at _blank_?', 
    a: [['company']]
  },
  {
    q: 'Describe your experience working with _blank_.', 
    a: [['project']]
  },
]

const languages = [
  'Java',
  'JavaScript',
  'PHP',
  'Perl',
  'C',
  'React',
  'AngularJS',
  'Haskell',
  'Akka',
  'C#',
  'Puppet',
  'Lapis',
  'Oracle Forms',
  'Yesod',
  'Express',
  'Factor',
  'Mercury',
  'Go (Pike)',
  'RPG',
  'OpenCyc',
  'Constraint-Handling Rules',
  'Simula 67',
  'Ermine',
  'REXX',
  'Simple Machines Forum',
  'XSB',
  'HAL/S',
  'Gerrit',
  'F--',
  'Cache ObjectScript',
  'template metaprogramming',
  'SNOBOL4',
  'PureScript',
  'PL/M',
  'MiniZinc',
  'Loci',
  'J',
  'Fortress',
  'PrologMUD',
  'Elm',
  'MongoDB',
  'AIML',
  'Potion',
  'Go! (McCabe)',
  'Curry',
  'Spray',
  'ASP',
  'Scala',
  'Clojure',
  'F#',
  'C++'
]

const companies = [
  'Walmart',
  'Berkshire Hathaway',
  'Apple',
  'Exxon Mobil',
  'McKesson',
  'UnitedHealth Group',
  'CVS Health',
  'General Motors',
  'AT&T',
  'Ford Motor',
  'AmerisourceBergen',
  'Amazon.com',
  'General Electric',
  'Verizon',
  'Cardinal Health',
  'Costco',
  'Walgreens Boots Alliance',
  'Kroger',
  'Chevron',
  'Fannie Mae',
  'J.P. Morgan Chase',
  'Express Scripts Holding',
  'Home Depot',
  'Boeing',
  'Wells Fargo',
  'Bank of America Corp.',
  'Alphabet',
  'Microsoft',
  'Anthem',
  'Citigroup',
  'Comcast',
  'IBM',
  'State Farm Insurance Cos.',
  'Phillips 66',
  'Johnson & Johnson',
  'Procter & Gamble',
  'Valero Energy',
  'Target',
  'Freddie Mac',
  'Lowe’s',
  'Dell Technologies',
  'MetLife',
  'Aetna',
  'PepsiCo',
  'Archer Daniels Midland',
  'UPS',
  'Intel',
  'Prudential Financial',
  'Albertsons Cos.',
  'United Technologies',
  'Marathon Petroleum',
  'Disney',
  'Humana',
  'Pfizer',
  'AIG',
  'Lockheed Martin',
  'Sysco',
  'FedEx',
  'Hewlett Packard Enterprise',
  'Cisco Systems',
  'HP',
  'Dow Chemical',
  'HCA Holdings',
  'Coca-Cola',
  'New York Life Insurance',
  'Centene',
  'American Airlines Group',
  'Nationwide',
  'Merck',
  'Cigna',
  'Delta Air Lines',
  'Best Buy',
  'Honeywell International',
  'Caterpillar',
  'Liberty Mutual Insurance Group',
  'Morgan Stanley',
  'Massachusetts Mutual Life Insurance',
  'Goldman Sachs Group',
  'Energy Transfer Equity',
  'TIAA',
  'Oracle',
  'Tyson Foods',
  'United Continental Holdings',
  'Allstate',
  'Publix Super Markets',
  'American Express',
  'TJX',
  'Nike',
  'Exelon',
  'General Dynamics',
  'Rite Aid',
  'Gilead Sciences',
  'CHS',
  '3M',
  'Time Warner',
  'Charter Communications',
  'Northwestern Mutual',
  'Facebook',
  'Travelers Cos.',
  'Capital One Financial',
  'Twenty-First Century Fox',
  'USAA',
  'World Fuel Services',
  'Philip Morris International',
  'Deere',
  'Kraft Heinz',
  'Tech Data',
  'Avnet',
  'Mondelez International',
  'Macy’s',
  'AbbVie',
  'McDonald’s',
  'DuPont',
  'Northrop Grumman',
  'ConocoPhillips',
  'Raytheon',
  'Tesoro',
  'Arrow Electronics',
  'Qualcomm',
  'Progressive',
  'Duke Energy',
  'Enterprise Products Partners',
  'Amgen',
  'US Foods Holding',
  'U.S. Bancorp',
  'Aflac',
  'Sears Holdings',
  'Dollar General',
  'AutoNation',
  'Community Health Systems',
  'Starbucks',
  'Eli Lilly',
  'International Paper',
  'Tenet Healthcare',
  'Abbott Laboratories',
  'Dollar Tree',
  'Whirlpool',
  'Southwest Airlines',
  'Emerson Electric',
  'Staples',
  'Plains GP Holdings',
  'Penske Automotive Group',
  'Union Pacific',
  'Danaher',
  'Southern',
  'ManpowerGroup',
  'Bristol-Myers Squibb',
  'Altria Group',
  'Fluor',
  'Kohl’s',
  'Lear',
  'Jabil Circuit',
  'Hartford Financial Services Group',
  'Thermo Fisher Scientific',
  'Kimberly-Clark',
  'Molina Healthcare',
  'PG&E Corp.',
  'Supervalu',
  'Cummins',
  'CenturyLink',
  'AECOM',
  'Xerox',
  'Marriott International',
  'Paccar',
  'General Mills',
  'PNC Financial Services Group',
  'American Electric Power',
  'Icahn Enterprises',
  'Nucor',
  'NextEra Energy',
  'Performance Food Group',
  'PBF Energy',
  'Halliburton',
  'CarMax',
  'Freeport-McMoRan',
  'Whole Foods Market',
  'Bank of New York Mellon',
  'Gap',
  'Omnicom Group',
  'Genuine Parts',
  'DaVita',
  'Colgate-Palmolive',
  'PPG Industries',
  'Goodyear Tire & Rubber',
  'Synchrony Financial',
  'DISH Network',
  'Visa',
  'Nordstrom',
  'INTL FCStone',
  'WestRock',
  'XPO Logistics',
  'Aramark',
  'CBS',
  'AES',
  'WellCare Health Plans',
  'FirstEnergy',
  'Conagra Brands',
  'Synnex',
  'CDW',
  'Textron',
  'Waste Management',
  'Illinois Tool Works',
  'Office Depot',
  'Monsanto',
  'Cognizant Technology Solutions',
  'Texas Instruments',
  'Lincoln National',
  'Newell Brands',
  'Land O’Lakes',
  'Marsh & McLennan',
  'Ecolab',
  'C.H. Robinson Worldwide',
  'Loews',
  'CBRE Group',
  'Kinder Morgan',
  'Kellogg',
  'Western Digital',
  'Guardian Life Ins. Co. of America',
  'Ross Stores',
  'L Brands',
  'J.C. Penney',
  'Farmers Insurance Exchange',
  'Reynolds American',
  'Viacom',
  'Becton Dickinson',
  'Micron Technology',
  'Principal Financial',
  'Arconic',
  'NRG Energy',
  'VF',
  'Devon Energy',
  'D.R. Horton',
  'Bed Bath & Beyond',
  'Consolidated Edison',
  'Edison International',
  'Sherwin-Williams',
  'NGL Energy Partners',
  'Dominion Energy',
  'Ameriprise Financial',
  'ADP',
  'Hilton Worldwide Holdings',
  'First Data',
  'Henry Schein',
  'Toys “R” Us',
  'BB&T Corp.',
  'Reinsurance Group of America',
  'Core-Mark Holding',
  'Biogen',
  'Las Vegas Sands',
  'Stanley Black & Decker',
  'Parker-Hannifin',
  'Stryker',
  'Estee Lauder',
  'Celgene',
  'BlackRock',
  'Xcel Energy',
  'CSX',
  'Unum Group',
  'Jacobs Engineering Group',
  'Lennar',
  'Group 1 Automotive',
  'Leucadia National',
  'Entergy',
  'PayPal Holdings',
  'Applied Materials',
  'Voya Financial',
  'Mastercard',
  'Priceline Group',
  'Liberty Interactive',
  'AutoZone',
  'State Street Corp.',
  'DTE Energy',
  'L3 Technologies',
  'HollyFrontier',
  'Praxair',
  'Universal Health Services',
  'Discover Financial Services',
  'Occidental Petroleum',
  'United States Steel',
  'Sempra Energy',
  'Baxter International',
  'W.W. Grainger',
  'Autoliv',
  'Norfolk Southern',
  'Baker Hughes',
  'Ally Financial',
  'Sonic Automotive',
  'Owens & Minor',
  'Huntsman',
  'Laboratory Corp. of America',
  'Murphy USA',
  'Advance Auto Parts',
  'Fidelity National Financial',
  'Air Products & Chemicals',
  'Hormel Foods',
  'Hertz Global Holdings',
  'MGM Resorts International',
  'Corning',
  'Republic Services',
  'Alcoa',
  'Fidelity National Information Services',
  'Pacific Life',
  'SunTrust Banks',
  'LKQ',
  'BorgWarner',
  'Ball',
  'CST Brands',
  'Public Service Enterprise Group',
  'Eastman Chemical',
  'eBay',
  'Mohawk Industries',
  'Oneok',
  'Frontier Communications',
  'Netflix',
  'American Family Insurance Group',
  'Thrivent Financial for Lutherans',
  'Expedia',
  'Lithia Motors',
  'Avis Budget Group',
  'Reliance Steel & Aluminum',
  'GameStop',
  'Tenneco',
  'O’Reilly Automotive',
  'Peter Kiewit Sons’',
  'United Natural Foods',
  'salesforce.com',
  'Boston Scientific',
  'Newmont Mining',
  'Genworth Financial',
  'Live Nation Entertainment',
  'Veritiv',
  'News Corp.',
  'Crown Holdings',
  'Global Partners',
  'PVH',
  'Level 3 Communications',
  'Navistar International',
  'Univar',
  'Campbell Soup',
  'Dick’s Sporting Goods',
  'Weyerhaeuser',
  'Mutual of Omaha Insurance',
  'Chesapeake Energy',
  'Anadarko Petroleum',
  'Interpublic Group',
  'J.M. Smucker',
  'Steel Dynamics',
  'Foot Locker',
  'Western Refining',
  'SpartanNash',
  'Dean Foods',
  'Zimmer Biomet Holdings',
  'PulteGroup',
  'W.R. Berkley',
  'Quanta Services',
  'EOG Resources',
  'Charles Schwab',
  'Eversource Energy',
  'Anixter International',
  'EMCOR Group',
  'Assurant',
  'CenterPoint Energy',
  'Harris',
  'HD Supply Holdings',
  'PPL',
  'Quest Diagnostics',
  'Williams',
  'WEC Energy Group',
  'Hershey',
  'AGCO',
  'Ralph Lauren',
  'Masco',
  'WESCO International',
  'LifePoint Health',
  'National Oilwell Varco',
  'Kindred Healthcare',
  'Mosaic',
  'Alliance Data Systems',
  'Computer Sciences',
  'Huntington Ingalls Industries',
  'Leidos Holdings',
  'Erie Insurance Group',
  'Tesla',
  'Ascena Retail Group',
  'Darden Restaurants',
  'Harman International Industries',
  'Nvidia',
  'R.R. Donnelley & Sons',
  'Fifth Third Bancorp',
  'Quintiles IMS Holdings',
  'Jones Lang LaSalle',
  'Dover',
  'Spirit AeroSystems Holdings',
  'Ryder System',
  'A-Mark Precious Metals',
  'Tractor Supply',
  'Sealed Air',
  'Auto-Owners Insurance',
  'Yum China Holdings',
  'Calpine',
  'Owens-Illinois',
  'Targa Resources',
  'Jones Financial (Edward Jones)',
  'JetBlue Airways',
  'Franklin Resources',
  'Activision Blizzard',
  'J.B. Hunt Transport Services',
  'Constellation Brands',
  'NCR',
  'Asbury Automotive Group',
  'American Financial Group',
  'Discovery Communications',
  'Berry Global Group',
  'Sanmina',
  'CalAtlantic Group',
  'Dr Pepper Snapple Group',
  'Dillard’s',
  'HRG Group',
  'CMS Energy',
  'Graybar Electric',
  'Builders FirstSource',
  'Yum Brands',
  'Casey’s General Stores',
  'Amphenol',
  'Oshkosh',
  'iHeartMedia',
  'TreeHouse Foods',
  'Alleghany',
  'Expeditors International of Washington',
  'Avery Dennison',
  'Ameren',
  'Hanesbrands',
  'Motorola Solutions',
  'St. Jude Medical',
  'Harley-Davidson',
  'Regions Financial',
  'Intercontinental Exchange',
  'Alaska Air Group',
  'Old Republic International',
  'Lam Research',
  'AK Steel Holding',
  'Rockwell Automation',
  'Adobe Systems',
  'Avon Products',
  'Terex',
  'NVR',
  'Dana',
  'Realogy Holdings',
  'American Tower',
  'Packaging Corp. of America',
  'Citizens Financial Group',
  'United Rentals',
  'Clorox',
  'Genesis Healthcare',
  'M&T Bank Corp.',
  'Ingredion',
  'UGI',
  'Owens Corning',
  'S&P Global',
  'Markel',
  'Wyndham Worldwide',
  'Arthur J. Gallagher',
  'Burlington Stores',
  'First American Financial',
  'Symantec',
  'Patterson',
  'Olin',
  'NetApp',
  'Raymond James Financial',
  'TravelCenters of America',
  'Fiserv',
  'Host Hotels & Resorts',
  'Insight Enterprises',
  'Mattel',
  'AmTrust Financial Services',
  'Cincinnati Financial',
  'Simon Property Group',
  'Western Union',
  'KeyCorp',
  'Delek US Holdings',
  'Booz Allen Hamilton Holding',
  'Chemours',
  'Western & Southern Financial Group',
  'Celanese',
  'Windstream Holdings',
  'Seaboard',
  'Essendant',
  'Apache',
  'Airgas',
  'Kelly Services',
  'Liberty Media',
  'Rockwell Collins',
  'Robert Half International',
  'CH2M Hill',
  'Big Lots',
  'Michaels Cos.',
  'Toll Brothers',
  'Yahoo',
  'Vistra Energy',
  'ABM Industries'
]

module.exports = {
  companies,
  languages,
  templates
}